### PR TITLE
Fixed bad memory reference bugs

### PR DESCRIPTION
**Pull request by nuggetwheat**
Hello,

This program crashes on my machine on some input without the following fixes.  Please merge them upstream.  I hereby grant you copyright to these code changes.  Thanks!

- Doug
  nuggetwheat@gmail.com

### CODE REVIEW

**Comment by moinejf** [comment]
Hi Doug,
I split your patch and applied the 2nd and 3rd differences.
But I do not understand the 1st diff. What is the problem with MAXFONTS?

**Comment by nuggetwheat** [comment]
When I put add the following code to the end of the dfont_set() function in
format.c:

        fprintf(stderr, "i=%d FONT_MAX=%d MAXFONTS=%d\n", i, FONT_MAX,
MAXFONTS);

        assert(i < MAXFONTS);

        return i;

The program asserts with the following output.


i=30 FONT_MAX=39 MAXFONTS=30

Assertion failed: (i < MAXFONTS), function dfont_set, file format.c, line
229.

Abort trap: 6

I think MAXFONTS and FONT_MAX need to be the same.  If I set MAXFONTS to
39, the problem goes away.

**Comment by moinejf** [comment]
FONT_MAX and MAXFONTS are used for different tables.

The table with the size FONT_MAX (font_tb[] in cfmt) is indexed by the type of the music elements that ask for a font (annotation, composer, footer,...). This table is purely static. Its size (FONT_MAX) is also static, and it is computed from the enum e_fonts and the number of dynamic fonts (setfont-x FONT_UMAX).

The tables with the size MAXFONTS contain the different fonts (name + encoding) found in the ABC source. These tables are dynamic. Each definiton %%xxxfont with a new couple (name+encoding) creates a new font. Then, the size of these tables must be limited.

So, there is no relation between the sizes of these different tables.

**Comment by nuggetwheat** [comment]
Except on line 262 of format.c you have:

        cfmt.anf = dfont_set(f);

then on line 1496 of parse.c you have:

        gch->font = cfmt.anf;

then on line 1651 of parse.c you have:

        str_font(gch->font);

which does the following:

void str_font(int ft)

{

        curft = defft = ft;

}


then in a couple of places in subs.c (838 && 881) the following call is
made:

         get_font_encoding(curft) == 0;  /* utf-8 font */


The get_font_encoding() function is defined as follows:

static char font_enc[MAXFONTS];         /* font encoding */

...

int get_font_encoding(int ft)

{

  return font_enc[ft];

}

So this is how the return value of dfont_set is used to index into an array
of size MAXFONTS.

- Doug

**Comment by moinejf** [comment]
Good catch!
The problem should be fixed.
Thanks.

**Comment by nuggetwheat** [comment]
No problem.  Thanks for being so responsive!

- Doug

**Comment by hkiel** [comment]
All problems of the original PR seem to be addressed. Can this be closed?

**Comment by moinejf** [comment]
Yes, indeed.

**Pull request closed without merging**
